name: Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      # gitに日本語ファイル名に対応させる。
      - run: git config --global core.quotepath false

      - run: sudo apt-get install -y nkf

      - run: npm run build-csv
      - run: npm run build-location-data
      - run: npm run build-standard-data
      - run: npm run build-api
      - run: npm run build-data-updates

      - name: Update README
        if: github.event_name == 'pull_request'
        run: |
          npm run build-readme
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if ! git diff --quiet README.md; then \
            git checkout $GITHUB_HEAD_REF; \
            git add README.md; \
            git commit -m "Update README"; \
            git push; \
          fi
          exit 0

      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: build
          path: build

  deploy:
    if: github.ref == 'refs/heads/main'

    # Allow one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true

    needs:
      - build

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # environment is not compatible with AWS credentials
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  pushcsv:
    if: github.event_name == 'pull_request'
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # All history

      - run: sudo apt-get install -y nkf
      - run: npm ci

      - run: npm run build-csv
      - run: |
          git switch "${GITHUB_HEAD_REF}"

          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

          git add data/**/*.csv

          if [[ -n "$(git diff --cached)" ]]; then
            git fetch origin
            git commit --message="CSV をアップデート"
            git push origin "${GITHUB_HEAD_REF}"
          fi
          exit 0

  backup:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    # Allow write on id-token so we can use it to authenticate to AWS
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::584344484091:role/takamatsu_github_s3_backup
          aws-region: ap-northeast-1

      - name: Backup data folder to S3 bucket
        run: |
          aws s3 sync data s3://takamatsu-city-opendata-backup-ap-northeast-1/${{ env.CURRENT_DATETIME }}
