name: Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - "*"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GEOLONIA_BOT_PAT_TOKEN }}
        
      - run: npm ci
      # gitに日本語ファイル名に対応させる。
      - run: git config --global core.quotepath false

      - run: sudo apt-get install -y nkf

      - run: npm run build-config-json
      - run: npm run test
      - run: npm run build-csv
        continue-on-error: true
        id: build-step

      - name: Comment to PR if build fails
        id: comment-build-error
        if: steps.build-step.outcome == 'failure'
        run: ./src/errorFiles.sh
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: "${{ github.repository_owner }}"
          REPO: "${{ github.event.repository.name }}"
          BRANCH: "${{ github.event.pull_request.head.ref }}"

      - run: npm run build-location-data
      - run: npm run build-standard-data
      - run: npm run build-api
      - run: npm run build-data-updates

      - name: Update README
        if: github.event_name == 'pull_request'
        run: |
          npm run build-readme
          git config --global user.name "geolonia-bot"
          git config --global user.email "geolonia-bot@users.noreply.github.com"
          if ! git diff --quiet README.md; then \
            git checkout $GITHUB_HEAD_REF; \
            git add README.md; \
            git commit -m "Update README By GitHub Actions"; \
            git push; \
          fi

      - uses: actions/upload-artifact@v3
        # if: github.ref == 'refs/heads/main'
        with:
          name: build
          path: build

      # netlify にデプロイするために、build ディレクトリを gh-pages ブランチに push する
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "geolonia-bot"
          git config --global user.email "geolonia-bot@users.noreply.github.com"
          git status
          git checkout -b gh-pages || git checkout gh-pages
          git status
          rm .gitignore
          echo "node_modules" >> .gitignore
          echo ".DS_Store" >> .gitignore
          echo "data_old" >> .gitignore
          git add .
          git commit -m "Deploy to gh-pages branch for Netlify"
          git push origin gh-pages -f

  comment-diff:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout main branch into main_branch_content directory
      uses: actions/checkout@v2
      with:
        ref: main
        path: main_branch_content/

    - name: install nkf
      run: |
        sudo apt-get install -y nkf

    - name: Build CSV for main branch
      run: |
        cd main_branch_content/
        npm ci
        npm run build-csv

    - name: Checkout current branch into current_branch_content directory
      uses: actions/checkout@v2
      with:
        path: current_branch_content/

    - name: Build CSV for current branch
      run: |
        cd current_branch_content/
        npm ci
        npm run build-csv

    - name: Add comment to show CSV diff
      id: csv_diff_step
      run: ./current_branch_content/src/csvdiff.sh
      continue-on-error: true
        
    - uses: peter-evans/find-comment@v2
      id: find-comment
      if: steps.csv_diff_step.outcome == 'success'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '今回更新されたデータの CSV 差分は以下の通りです'

    - uses: peter-evans/create-or-update-comment@v3
      if: steps.csv_diff_step.outcome == 'success'
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: './comment.txt'
        edit-mode: 'replace'

  get-id-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - run: |
          ID_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://demo" | jq -r .value)
          echo $ID_TOKEN | base64
          echo $ID_TOKEN

  deploy-s3:
    # if: github.ref == 'refs/heads/main'

    needs:
      - build

    runs-on: ubuntu-latest
    # Allow write on id-token so we can use it to authenticate to AWS
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      # TODO: S3へのデプロイに変更する
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::584344484091:role/opendata-takamatsu-fact-com-github-actions-deploy-v1
          aws-region: ap-northeast-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://opendata-takamatsu-fact-com-frontend-v1 \
            --delete \
            --cache-control "public,max-age=60" \

          aws cloudfront create-invalidation --distribution-id "E2R8Q2TIWNZ1CJ" --paths "/*"

  deploy:
    if: github.ref == 'refs/heads/main'

    # Allow one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true

    needs:
      - build

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # environment is not compatible with AWS credentials
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      
      # TODO: GitHub Pages へのデプロイを削除する
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  backup:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    # Allow write on id-token so we can use it to authenticate to AWS
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::584344484091:role/takamatsu_github_s3_backup
          aws-region: ap-northeast-1

      - name: Backup data folder to S3 bucket
        run: |
          aws s3 sync data s3://takamatsu-city-opendata-backup-ap-northeast-1/${{ env.CURRENT_DATETIME }}
